#!/bin/bash
# WARNING: this script will destroy data on the selected disk.
# This script can be run by executing the following:
#   curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/inst-desktop | bash
set -uo pipefail
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

ker=D44S; kver='6.12.12-12'
mpdver=0.23.17-36
mympdver=20.0.0-1
lmsver=9.1-1

c_blue_b=$'\e[1;38;5;27m'
c_green_b=$'\e[1;38;5;46m'
c_red_b=$'\e[1;38;5;196m'
c_red=$'\e[1;33m'
c_white=$'\e[m'
c_white_b=$'\e[1;37m'
c_gray=$'\e[0;37m'

echo root:archq | chpasswd
### Get infomation from user ###
password(){
    password=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Enter admin password" 0 0) || exit 1; clear
    if [[ -z "$password" ]];then
        dialog --stdout --title "ArchQ Desktop" --pause "\n Passwd cannot be empty.\n\n Setting password again." 12 0 3 || exit 1; clear
        password
    fi
    password2=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Enter password again" 0 0) || exit 1; clear
    if [[ "$password" != "$password2" ]]; then
        dialog --stdout --title "ArchQ Desktop" --pause "\n Passwd did not match.\n\n Setting password again." 12 0 3 || exit 1; clear
        password
    fi
}

hostname=ArchQ
# hostname=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Enter hostname" 0 0) || exit 1; clear
# if [ -z "$hostname" ];then
#     dialog --stdout --title "ArchQ Desktop" --pause "\n Hostname cannot be empty.\n\n Default will be 'ArchQ'." 12 0 3 || exit 1; clear
#     hostname=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Enter hostname again" 0 0) || exit 1; clear
# fi

user=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Enter the admin username" 0 0) || exit 1; clear
if [ -z "$user" ];then
    dialog --stdout --title "ArchQ Desktop" --pause "\n Username cannot be empty.\n\n Default will be 'archq'." 12 0 3 || exit 1; clear
    user=archq
    user=$(dialog --stdout --title "ArchQ Desktop" --inputbox "Please re-enter the admin username." 0 0) || exit 1; clear
fi
password
lang=$(dialog --stdout --title "ArchQ Desktop" --menu "Select language" 7 0 0 E "English" J "Japanese" T "Chinese TW") || exit 1; clear
devicelist=$(lsblk -dplnx size -o name,size | grep -Ev "boot|rpmb|loop" | tac)
device=$(dialog --stdout --title "ArchQ" --menu "Select installation disk" 0 0 0 ${devicelist}) || exit 1; clear
fmt=$(dialog --stdout --title "ArchQ" --menu "Format device ${device}" 7 0 0 E Entire P "Partition / Retain Music" U "USB Storage") || exit 1; clear
if [ $fmt = P ]; then
    partlst='dialog --stdout --title "Device $device" --menu "Select partition" 7 0 0 '
    while read line; do
        partname=$(echo $line | awk '{print $1}')
        partlable=$(echo $line | awk '{print substr($0,index($0,$2))}')
        partlst+=$partname' '\"$partlable\"' '
    done <<< $(lsblk -pln -o name,size,partlabel,fstype $device | sed -e '1d')
    part_root=$(eval $partlst) || exit 1; clear
    part_boot=$(lsblk -pln -o name,parttypename | grep EFI | grep $device | awk 'NR==1 {print $1}')
fi

echo ${device} | grep -q 'nvme' && f2fs=F || f2fs=X
ifport=$(ip -o link show | awk '{print $2,$9}' | grep -m1 '^en.*UP' | sed 's/:.*//')
ip=$(dialog --stdout --title "ArchQ" --menu "${ifport} IP setting" 7 0 0 D "DHCP" S "Static IP") || exit 1; clear
if [ $ip = S ]; then
ifmask=24; ifdns=8.8.8.8
ifconfig=$(dialog --stdout --title "ArchQ Desktop" --ok-label "Ok" --form "Enter $ifport IP setting" 10 35 0 \
            "Address" 1 1   "192.168.1."    1 10 15 0 \
            "Netmask" 2 1   "$ifmask"       2 10 15 0 \
            "Gateway" 3 1   "192.168.1.254" 3 10 15 0 \
            "DNS"     4 1   "$ifdns"        4 10 15 0) || exit 1; clear
ifaddr=$(echo $ifconfig | cut -d' ' -f1)
ifmask=$(echo $ifconfig | cut -d' ' -f2)
ifgw=$(echo $ifconfig | cut -d' ' -f3)
ifdns=$(echo $ifconfig | cut -d' ' -f4)
fi
desktop=LXDE
# desktop=$(dialog --stdout --title "ArchQ Desktop" \
#     --menu "Desktop & VNC :5901" 7 0 0 \
#     LXDE "Lightweight X11 Desktop" \
#     LXQt "Lightweight Qt Desktop" \
#     VNC "TigerVNC only" ) || exit 1; clear
server=$(dialog --stdout --title "ArchQ Desktop" \
    --menu "Select music server" 7 0 0 \
    MPD "MPD & myMPD web-based client" \
    LMS "Lyrion Music Server" \
    None "Desktop only" ) || exit 1; clear
### select sound card
scard="hw:0,0"

### Set up logging ###
exec 1> >(tee "stdout.log")
exec 2> >(tee "stderr.log")

timedatectl set-ntp true

mkboot(){
    mkfs.vfat -F32 "${part_boot}"
}

# Foramt and install in one partition
old_efi=''
if [ $fmt = P ]; then
    # Rebuild partition if EFI < 200MB
    if [ $(lsblk $part_boot -pln -o size | tr -d [:alpha:]) -lt 200 ]; then
        boot_start=$(parted $device 'unit s' print | grep "^ ${part_root: -1}" | tail -1 | awk -F '[[:space:]]*' '{ print $3 }')
        boot_end=$(expr ${boot_start::-1} + 786431)s
        root_start=$(expr ${boot_start::-1} + 786432)s
        parted --script "${device}" -- \
            rm "${part_root:0-1}" \
            mkpart EFI fat32 $boot_start $boot_end \
            set "${part_root:0-1}" boot on \
            mkpart ArchQ ext4 $root_start 100%
        old_efi=$part_boot
        part_boot=$part_root
        part_root=$(ls ${device}* | grep -E "^${device}p?$((${part_root:0-1} + 1))$")
        # Format boot partition (EFI/ESP)
        mkboot
    fi
else
    # Install in entire disk
    [ $server = LMS ] && root_size=6144 || root_size=5120
    root_end=$(( $root_size + 257 + 1 ))MiB
  parted --script "${device}" -- mklabel gpt \
        mkpart EFI fat32 1MiB 385MiB \
    set 1 boot on \
        mkpart ArchQ ext4 385MiB ${root_end} \
        mkpart Database ext4 ${root_end} 100%

# Simple globbing was not enough as on one device I needed to match /dev/mmcblk0p1 
# but not /dev/mmcblk0boot1 while being able to match /dev/sda1 on other devices.
part_boot="$(ls ${device}* | grep -E "^${device}p?1$")"
    part_root="$(ls ${device}* | grep -E "^${device}p?2$")"
    # Format boot partition (EFI/ESP)
    mkboot
fi

# format root partition
[ $f2fs = F ] && mkfs.f2fs -fl ArchQ "${part_root}" || mkfs.xfs -fL ArchQ "${part_root}"
# Wipe & format data partition
part_data="$(ls ${device}* | grep -E "^${device}p?3$")"
wipefs "${part_data}"
[ $f2fs = F ] && mkfs.f2fs -fl Data "${part_data}" || mkfs.xfs -fL Data "${part_data}"

## Mount root & boot partition
mount "${part_root}" /mnt
mkdir /mnt/boot
mount "${part_boot}" /mnt/boot

cpu=intel; cat /proc/cpuinfo | grep -q AMD && cpu=amd
[ -f /mnt/boot/${cpu}-ucode.img ] || pacstrap /mnt ${cpu}-ucode

echo -e "\n${c_blue_b}Install Arch Linux package ...${c_gray}\n"
lxd=''
[ $desktop = LXDE ] && lxd="lxdm noto-fonts-cjk midori cantata fcitx5-im fcitx5-configtool falkon lxde lxpanel"
[ $desktop = LXQt ] && lxd="lxdm noto-fonts-cjk midori cantata fcitx5-im fcitx5-configtool falkon lxqt xdg-utils breeze-icons fcitx5-qt fcitx5-chewing fcitx5-mozc"
pacstrap /mnt base linux-firmware grub efibootmgr mkinitcpio os-prober gptfdisk f2fs-tools xfsprogs openssh dhclient \
        vim nano wget avahi sudo dialog cpupower lm_sensors ntp hdparm htop iwd nocache \
        which glibc cifs-utils icu parted scrub mc usbutils tmux rsync nfs-utils \
        fmt libcdio libupnp liburing cdparanoia libcdio-paranoia libcddb libmad \
        perl-webservice-musicbrainz perl-musicbrainz-discid perl-net-ssleay perl-io-socket-ssl perl-uri perl-mojolicious \
        alsa-lib mpc mympd rc-local libid3tag taglib lua \
        tigervnc upplay xf86-video-fbdev audacious deadbeef-static ${lxd}
[ $desktop = LXDE ] && arch-chroot /mnt pacman -R --noconfirm lxmusic
[ $desktop = LXQt ] && arch-chroot /mnt pacman -R --noconfirm lxqt-powermanagement

genfstab -Up /mnt | sed '/^$/d' >>/mnt/etc/fstab
sed -i 's/barrier,//g;s/relatime,lazytime/noatime/g;s/nodiscard,//g' /mnt/etc/fstab
cat >>/mnt/etc/fstab <<EOF
none /tmp tmpfs nodev,nosuid,mode=1777 0 0
none /var/log tmpfs nodev,nosuid,noexec,size=10M 0 0
none /var/tmp tmpfs nodev,nosuid,noexec,size=20M 0 0
EOF

echo "${hostname}" > /mnt/etc/hostname
echo -e "nameserver 8.8.8.8\nnameserver 1.1.1.1" >> /mnt/etc/resolv.conf
arch-chroot /mnt useradd -mU "$user"
sed -i '0,/# %wheel/s/# %wheel/%wheel/' /mnt/etc/sudoers
arch-chroot /mnt usermod -aG wheel $user
echo "$user $hostname =NOPASSWD: /usr/bin/systemctl poweroff,/usr/bin/systemctl halt,/usr/bin/systemctl reboot,/usr/bin/qboot,/usr/bin/config" >>/mnt/etc/sudoers

### Set locale language
echo -e "en_US.UTF-8 UTF-8\nja_JP.UTF-8 UTF-8\nzh_TW.UTF-8 UTF-8" >/mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
[ $lang = J ] && echo "LANG=ja_JP.UTF-8" > /mnt/etc/locale.conf
[ $lang = T ] && echo "LANG=zh_TW.UTF-8" > /mnt/etc/locale.conf
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime
[ $lang = J ] && arch-chroot /mnt ln -sf /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

# echo "$user:$password" | chpasswd --root /mnt
arch-chroot /mnt sh -c "echo $user:$password | chpasswd"
# echo "root:$password" | chpasswd --root /mnt
arch-chroot /mnt sh -c "echo root:$password | chpasswd"

### Ethernet IP
echo ......................
echo "[Match]" >/mnt/etc/systemd/network/10-${ifport}.network
echo -e "Name=${ifport}\n" >>/mnt/etc/systemd/network/10-${ifport}.network
echo "[Network]" >>/mnt/etc/systemd/network/10-${ifport}.network
if [ $ip = D ]; then
    echo Install DHCP Client...
    echo "DHCP=ipv4" >>/mnt/etc/systemd/network/10-${ifport}.network
    arch-chroot /mnt systemctl enable avahi-daemon
else
    echo "Address=$ifaddr/$ifmask" >>/mnt/etc/systemd/network/10-${ifport}.network
    echo "Gateway=$ifgw" >>/mnt/etc/systemd/network/10-${ifport}.network
    echo "DNS=$ifgw $ifdns" >>/mnt/etc/systemd/network/10-${ifport}.network
fi
arch-chroot /mnt systemctl enable systemd-networkd

## Add Ethernet dectect to rc.local
sed -i '$d' /mnt/etc/rc.local
cat >>/mnt/etc/rc.local <<EOF
set +e

#touch /root/\$(uname -r)
# ethernet auto detect
while read ether; do
    npath='/etc/systemd/network/'
    #touch \${npath}\${ether}_\$(uname -r | cut -d- -f3)
    if [ ! -f "\$npath""10-\${ether}.network" ]; then
        cd \$npath
        source=\$(ls 10-en*.network | head -n 1)
        cp \$source 10-\${ether}.network
        sed -i 's/Name=.*/Name='"\$ether"'/' 10-\${ether}.network
        systemctl restart systemd-networkd
        cd -
    fi
done <<< \$(ip -o link show | awk '{print \$2,\$9}' | grep '^en' | cut -d':' -f1)
sleep 1

EOF

arch-chroot /mnt sh -c 'yes | pacman -Scc'
rm -rf /mnt/etc/pacman.d/gnupg
arch-chroot /mnt pacman-key --init
arch-chroot /mnt pacman-key --populate archlinux
sed -i '84,85 s/^/#/' /mnt/etc/pacman.conf
arch-chroot /mnt pacman -Sy

sed -i 's/^#\?GRUB_DISABLE_OS_PROBER/GRUB_DISABLE_OS_PROBER/;s/^#\?GRUB_DISABLE_SUBMENU=.*$/GRUB_DISABLE_SUBMENU=y/' /mnt/etc/default/grub
sed -i 's/loglevel=3/loglevel=0 nohz=off idle=poll rcu_nocb_poll rcu.blimit=0 relax_domain_level=0 skew_tick=0 nosmt noirqdebug no_timer_check clocksource=tsc tsc=reliable tsc=noirqtime tsc=nowatchdog hpet=disable iomem=relaxed ipv6.disable=1 vsyscall=none/' \
/mnt/etc/default/grub
arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --removable --bootloader-id=$hostname

echo $device | grep -q nvme && sed -i 's/MODULES=()/MODULES=(nvme)/' /mnt/etc/mkinitcpio.conf
[ $f2fs = X ] && sed -i 's/MODULES=()/MODULES=(xfs)/' /mnt/etc/mkinitcpio.conf

### Kernel
echo -e "\n${c_blue_b}Install ArchQ Kernel ...${c_gray}\n"
arch-chroot /mnt wget -P /root https://raw.githubusercontent.com/sam0402/ArchQ/main/kernel/linux-${ker}-${kver}-x86_64.pkg.tar.zst
arch-chroot /mnt pacman -U --noconfirm /root/linux-${ker}-${kver}-x86_64.pkg.tar.zst
arch-chroot /mnt mkinitcpio -p linux-${ker}
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

cpus=$(getconf _NPROCESSORS_CONF)
### Setup Desktop (LXDE || LXQt)
echo "LANG=en_US.UTF-8" >/mnt/home/$user/.xinitrc
[ $lang = J ] && echo "LANG=ja_JP.UTF-8" > /mnt/home/$user/.xinitrc
[ $lang = T ] && echo "LANG=zh_TW.UTF-8" > /mnt/home/$user/.xinitrc

echo "GTK_IM_MODULE=fcitx" >>/mnt/etc/environment
echo "QT_IM_MODULE=fcitx" >>/mnt/etc/environment
echo "XMODIFIERS=@im=fcitx" >>/mnt/etc/environment
[ $desktop = LXDE ] && arch-chroot /mnt ln -s /usr/bin/lxterminal /usr/bin/xterm
[ $desktop = LXQt ] && arch-chroot /mnt ln -s /usr/bin/qterminal /usr/bin/xterm
[ $desktop = LXDE ] && sed -i 's;^# session=/usr/bin/startlxde;session=/usr/bin/startlxde;g' /mnt/etc/lxdm/lxdm.conf
[ $desktop = LXQt ] && sed -i 's;^# session=/usr/bin/startlxde;session=/usr/bin/startlxqt;g' /mnt/etc/lxdm/lxdm.conf

# Setup TigerVNC
# chroot /mnt ln /usr/lib/systemd/system/vncserver\@.service /etc/systemd/system/vncserver\@:1.service
# echo ":1=$user" >>/mnt/etc/tigervnc/vncserver.users
# mkdir /mnt/home/$user/.vnc
# [ $desktop = LXDE ] && echo "session=LXDE" >/mnt/home/$user/.vnc/config
# [ $desktop = LXQt ] && echo "session=lxqt" >/mnt/home/$user/.vnc/config
# arch-chroot /mnt sh -c "echo $password | vncpasswd -f >/home/$user/.vnc/passwd"
# arch-chroot /mnt chmod 600 /home/$user/.vnc/passwd
# arch-chroot /mnt chown -R ${user}: /home/$user/.vnc
# arch-chroot /mnt systemctl enable vncserver@:1.service
[ $desktop = VNC ] || arch-chroot /mnt systemctl enable lxdm

mkdir /mnt/home/$user/Desktop /mnt/mnt/music
arch-chroot /mnt chown -R ${user}: /home/$user/Desktop /mnt/music
cat >>/mnt/home/$user/Desktop/Config.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Config
Type=Application
Terminal=true
Exec=sudo /usr/bin/config.sh
EOF

## server
case $server in
    LMS)
        echo -e "\n${c_blue_b}Install Lyrion Music Server ...${c_gray}\n"
        arch-chroot /mnt wget -P /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/lyrionmusicserver-8.4.0-1-x86_64.pkg.tar.xz
        arch-chroot /mnt pacman -U --noconfirm /root/lyrionmusicserver-8.4.0-1-x86_64.pkg.tar.xz
        sed -i 's/novideo/novideo --charset=utf8/' /mnt/usr/lib/systemd/system/lyrionmusicserver.service
        sed -i 's|ExecStart=|ExecStart=/usr/bin/pagecache-management.sh |' /mnt/usr/lib/systemd/system/lyrionmusicserver.service
        arch-chroot /mnt systemctl enable lyrionmusicserver
        cat >>/mnt/home/$user/Desktop/lms.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Lyrion Music Server
Type=Link
URL=http://localhost:9000/
Icon=text-html
EOF
        ;;
    MPD)
        echo -e "\n${c_blue_b}Install MPD ...${c_gray}\n"
        arch-chroot /mnt wget -qP /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/mpd-dsd-${mpdver}-x86_64.pkg.tar.zst
        arch-chroot /mnt wget -qP /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/mpd_cdrom-1.0.0-1-any.pkg.tar.zst
        arch-chroot /mnt wget -qP /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/flac-1.4.3-1-x86_64.pkg.tar.zst
        arch-chroot /mnt pacman -U --noconfirm /root/mpd-dsd-${mpdver}-x86_64.pkg.tar.zst /root/mpd_cdrom-1.0.0-1-any.pkg.tar.zst /root/flac-1.4.3-1-x86_64.pkg.tar.zst
        sed -i 's|ExecStart=|ExecStart=/usr/bin/pagecache-management.sh |' /mnt/usr/lib/systemd/system/mpd.service
        ### Install myMPD
        arch-chroot /mnt wget -P /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/mympd-${mympdver}-x86_64.pkg.tar.zst
        arch-chroot /mnt wget -qP /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/libnewt-0.52.24-2-x86_64.pkg.tar.zst
        arch-chroot /mnt pacman -U --noconfirm /root/mympd-${mympdver}-x86_64.pkg.tar.zst
        mkdir -p /mnt/var/lib/private/mympd/config/
        echo 'Unknown' >/mnt/var/lib/private/mympd/config/album_group_tag
        arch-chroot /mnt systemctl enable mpd mympd
### setup mpd
        [[ -n "$scard" ]] && sed -i 's/^#\?.* \?\tdevice.*"/\tdevice '"\"$scard\""'/' /mnt/etc/mpd.conf
        sed -i 's/album,title/album,albumartist,title/' /mnt/etc/mpd.conf
        sed -i 's/^include_optional/#include_optional/g' /mnt/etc/mpd.conf
#### add priority for MPD
        cat >>/mnt/etc/rc.local <<EOF
if systemctl is-active mpd >/dev/null; then
    mpc enable ArchQ >/dev/null 2>&1
    chrt -fp 85 \$(pgrep mpd)
    chrt -p 90 \$(ps -T -C mpd -o tid,comm= | awk '\$2=="player"{print \$1}')
    chrt -fp 54 \$(pgrep ksoftirqd/\$(ps -eLo comm,cpuid| grep "output:A"|awk '{print \$2}'))
fi

EOF
        cat >>/mnt/home/$user/Desktop/myMPD.desktop <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=myMPD
Type=Link
URL=https://localhost/
Icon=text-html
EOF

### Start mpd.. etc. service
        arch-chroot /mnt systemctl disable mpd.socket
        arch-chroot /mnt usermod -aG optical mpd
        ;;
esac

### Other setting
echo -e "\n${c_blue_b}Setting service ...${c_gray}\n"
arch-chroot /mnt wget -qP /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/ffmpeg-2%3A6.0-5-x86_64.pkg.tar.zst
arch-chroot /mnt pacman -U --noconfirm /root/ffmpeg-2:6.0-5-x86_64.pkg.tar.zst
## Instal alsa-lib-1.1.9
cp /archq/alsa-utils-1.2.8-1-x86_64.pkg.tar.zst /mnt/root
arch-chroot /mnt wget -P /root https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/alsa-lib-1.1.9-8-x86_64.pkg.tar.zst
arch-chroot /mnt pacman -U --noconfirm --overwrite '*' /root/alsa-lib-1.1.9-8-x86_64.pkg.tar.zst
arch-chroot /mnt pacman -Udd --noconfirm /root/alsa-utils-1.2.8-1-x86_64.pkg.tar.zst

cat >>/mnt/etc/rc.local <<EOF
systemctl stop systemd-journald-dev-log.socket systemd-journald.socket systemd-journald
# systemctl stop systemd-udevd-kernel.socket systemd-udevd-control.socket systemd-udevd 
# systemctl stop systemd-networkd

exit 0
EOF
arch-chroot /mnt systemctl enable sshd ntpdate rc-local cpupower
arch-chroot /mnt systemctl disable ntpd
arch-chroot /mnt ln -s /usr/bin/vim /usr/bin/vi
###
echo 'ACTION=="add", SUBSYSTEM=="pci", ATTR{power/control}="auto"' >/mnt/etc/udev/rules.d/pci_pm.rules
cat >/mnt/etc/udev/rules.d/60-ioschedulers.rules <<EOF
# set scheduler for NVMe
ACTION=="add|change", KERNEL=="nvme[0-9]n[0-9]", ATTR{queue/scheduler}="none"
# set scheduler for SSD and eMMC
ACTION=="add|change", KERNEL=="sd[a-z]|mmcblk[0-9]*", ATTR{queue/rotational}=="0", ATTR{queue/scheduler}="kyber"
# set scheduler for rotating disks
ACTION=="add|change", KERNEL=="sd[a-z]", ATTR{queue/rotational}=="1", ATTR{queue/scheduler}="bfq"
EOF
cat >/mnt/etc/udev/rules.d/69-hdparm.rules <<EOF
ACTION=="add|change", KERNEL=="sd[a-z]", ATTRS{queue/rotational}=="1", RUN+="/usr/bin/hdparm -a0 /dev/%k"
EOF
curl -sL https://raw.githubusercontent.com/bb-qq/r8152/master/50-usb-realtek-net.rules >/mnt/etc/udev/rules.d/50-usb-realtek-net.rules
# USB Affinity
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/usb-affinity.service >/mnt/usr/lib/systemd/system/usb-affinity.service
cpu_mask=$(printf "%x" $((1<<(cpus-1))))
sed -i "s/echo 20/echo $cpu_mask/" /mnt/usr/lib/systemd/system/usb-affinity.service
arch-chroot /mnt systemctl enable usb-affinity

## Patch
sed -i 's/#Storage=auto/Storage=none/' /mnt/etc/systemd/journald.conf
sed -i 's/wait-online/wait-online --any/' /mnt/usr/lib/systemd/system/systemd-networkd-wait-online.service
sed -i '/Service/iAfter=mpd.service\n' /mnt/usr/lib/systemd/system/rc-local.service

# Desktop auto login
[ $desktop = V ] || sed -i 's/# autologin=.*/autologin='"$user"'/;s/# timeout=.*/timeout=0/' /mnt/etc/lxdm/lxdm.conf
### install config file
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/update >/mnt/root/.update
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/timezone.sh >/mnt/usr/bin/timezone.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/ether-cfg.sh >/mnt/usr/bin/ether-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/kernel-cfg.sh >/mnt/usr/bin/kernel-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/cpu-cfg.sh >/mnt/usr/bin/cpu-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/partimnt-cfg.sh >/mnt/usr/bin/partimnt-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/update_scpt.sh >/mnt/usr/bin/update_scpt.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/desktop-cfg.sh >/mnt/usr/bin/desktop-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/mpd-cfg.sh >/mnt/usr/bin/mpd-cfg.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/config.sh >/mnt/usr/bin/config.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/qboot >/mnt/usr/bin/qboot
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/usb-storage-mount.sh >/mnt/usr/bin/usb-storage-mount.sh
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/pkg/90-usb-storage-automount.rules >/mnt/etc/udev/rules.d/90-usb-storage-automount.rules
curl -sL https://raw.githubusercontent.com/sam0402/ArchQ/main/config/pagecache-management.sh >/mnt/usr/bin/pagecache-management.sh
arch-chroot /mnt wget -qP /usr/bin https://raw.githubusercontent.com/sam0402/ArchQ/main/config/pagecache-management.so
chmod +x /mnt/usr/bin/*.sh /mnt/usr/bin/qboot /mnt/home/$user/Desktop/*.desktop
arch-chroot /mnt ln -s /usr/bin/config.sh /usr/bin/config

cat >>/mnt/home/${user}/.bashrc <<EOF
\$(uname -r | grep -q Qrip) && PSC=36 || PSC=31
export KVER=\$(uname -r | cut -d- -f3)
alias ...='cd ../../'
alias dir='command ls -lSrah'
alias egrep='egrep --color=auto'
alias grep='grep --color=auto'
alias ll='command ls -l --color=auto -v'
alias ls='command ls --color=auto -v'
alias poweroff='sudo systemctl poweroff'
alias reboot='sudo systemctl reboot'
alias qboot='sudo qboot'
alias config='sudo config.sh'
alias df='df -h'
alias status='systemctl status'
EOF
sed -i 's/\\h/\\h:\\[\\e[${PSC}m\\]$KVER\\[\\e[m\\]/' /mnt/home/${user}/.bashrc

cat >>/mnt/root/.bashrc <<EOF
\$(uname -r | grep -q Qrip) && PSC=36 || PSC=31
export KVER=\$(uname -r | cut -d- -f3)
PS1='[\u@\h:\[\e[\${PSC}m\]\$KVER\[\e[m\] \W]\\$ '
alias ...='cd ../../'
alias dir='command ls -lSrah'
alias egrep='egrep --color=auto'
alias grep='grep --color=auto'
alias ll='command ls -l --color=auto -v'
alias ls='command ls --color=auto -v'
alias df='df -h'
alias status='systemctl status'
EOF
rm -f /mnt/root/*.tar.zst /mnt/root/*.tar.xz
# Detect other OS
if [ -n "$old_efi" ]; then
    arch-chroot /mnt mount "$old_efi" /mnt
    arch-chroot /mnt os-prober
    sleep 2
    arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
fi

dialog --stdout --title "ArchQ Desktop" --pause "\n ArchQ has been installed.\nPlease unplug the USB drive.\n\nThe system will reboot in 10 seconds." 12 50 10; clear
reboot
