#!/bin/bash
config='/etc/srvmode.conf'
c_red_b=$'\e[1;38;5;196m'
c_gray=$'\e[0;37m'
c_write=$'\e[m'

n=1; options=()
while read line; do
    options[$n]=${line}
    ((n += 1 ))
done <<< $(cat $config | sed '1d' | awk -F: '{print $1}')

input=$1
if [ ! $1 ]; then
    for i in ${!options[@]}; do
        echo "$i" "${options[i]}"
        (( n += 1 ))
    done
    echo -n "Select mode to boot: "
    read input
fi

sudo sed -i '1s/Active=.*/Active='"${options[$input]}"'/' $config
qboot=$(cat $config | sed '1d' | grep "${options[$input]}" | awk -F: '{print $3}')
echo "ArchQ change to mode '${c_red_b}${options[$input]}'${c_write}."
sudo qboot $qboot
echo -n "Reboot now [Y/n]? "
input=''; read input
[[ -z $input || $input = y ]] && reboot
