#!/bin/bash
# systemctl is-active pulseaudio >/dev/null 2>&1 || systemctl --user --now enable pulseaudio

while read line; do
    names+=$line' '
done <<< $(pactl list sinks | grep -E "Name:" | cut -d- -f3-4)

while read line; do
    desc+=${line//[[:blank:]]/}' '
done <<< $(pactl list sinks | grep -E "Description:" | cut -d: -f2)

a_name=($names)
a_desc=($desc)

for ((i=0; i < ${#a_name[@]}; i++))
do
     menu+=$i' '${a_desc[$i]}' '
done

sel=$(dialog --stdout \
        --title "ArchQ $1" \
        --menu "Select Airport ouput to" 7 0 0 $menu) || exit 1

pactl set-default-sink raop-sink-${a_name[$sel]}
echo ${a_desc[$sel]} >~/.config/pipewire/default_sink
echo Airplay to ${a_desc[$sel]}.