#!/bin/bash
grub_def='/etc/default/grub'
grub_cfg='/boot/grub/grub.cfg'
kernel=linux-$(uname -r | awk -F - '{print $3}')
iso_1st=$(($(getconf _NPROCESSORS_ONLN)-1))
isocpu="isolcpus=$iso_1st rcu_nocbs=$iso_1st "
c_red_b=$'\e[1;38;5;196m'
c_gray=$'\e[0;37m'
c_write=$'\e[m'
mkgrub(){
    if lsblk -pln -o name,partlabel | grep -q Microsoft; then
        part_boot=$(lsblk -pln -o name,parttypename | grep EFI | awk 'NR==1 {print $1}')
        mount "$part_boot" /mnt
        sleep 2
        os-prober | grep -q Windows || umount /mnt
    fi
    grub-mkconfig -o $grub_cfg
    pacman -Q ramroot >/dev/null 2>&1 && sed -i 's/fallback/ramroot/g' $grub_cfg
}

n=1; options=()
while read line; do
    options[$n]=${line}
    ((n += 1 ))
done <<< $(grep 'menuentry ' $grub_cfg | cut -d "'" -f2 | sed '$d;s/Arch Linux, with Linux //;s/ initramfs//'|cut -d' ' -f1-2)

[ "${options[$1]}" == "$kernel" ] && exit 1

input=$1
if [ ! $1 ]; then
    for i in ${!options[@]}; do
        $(echo ${options[i]} | grep -qv 'fallback') && echo "$i" "${options[i]}"
        (( n += 1 ))
    done
    echo -n "Select kernel to boot: "
    read input
fi

[ -z $input ] && input=1

if [ ! -d /opt/logitechmediaserver ]; then
    [ $input = 1 ] && sed -i 's/GRUB_CMDLINE_LINUX=.*/GRUB_CMDLINE_LINUX="'"$isocpu"'"/' $grub_def || sed -i 's/'"$isocpu"'//g' $grub_def
fi

(( boot = input -1 ))
sed -i 's/^#\?GRUB_DEFAULT=.*$/GRUB_DEFAULT='"$boot"'/' $grub_def
mkgrub

echo -n "ArchQ will boot with '${c_red_b}${options[$input]}${c_write}', reboot now [Y/n]?"
input=''; read input
[[ -z $input || $input = y ]] && reboot
[[ $input = p ]] && poweroff
