#!/bin/bash
grub_def='/etc/default/grub'
isocpu='isolcpus=1 rcu_nocbs=1 irqaffinity=0,2,3,4,5,6,7 '

n=2;
options=()
while read line; do
    options[ ((n / 2 )) ]=${line}
    ((n += 2 ))
done <<< $(grep 'with' /boot/grub/grub.cfg | grep -v 'fallback' | cut -d "'" -f2 | cut -d ' ' -f5)

input=$1
if [ ! $1 ]; then
    for i in ${!options[@]}; do
        echo "$i" "${options[i]}"
        (( n += 1 ))
    done
    echo -n "Select kernel to boot: "
    read input
fi

[ -z $input ] && input=1

if [ ! -d /opt/logitechmediaserver ]; then
    [ $input = 1 ] && sed -i 's/idle=poll /idle=poll '"$isocpu"'/' $grub_def || sed -i 's/'"$isocpu"'//g' $grub_def
fi

(( boot = input * 2 - 2 ))
sed -i 's/^#\?GRUB_DEFAULT=.*$/GRUB_DEFAULT='"$boot"'/' $grub_def
grub-mkconfig -o /boot/grub/grub.cfg

echo "......"
echo -n "ArchQ will boot with '${options[$input]}', reboot now [Y/n]? "
input=''
read input
[[ -z $input || $input = y ]] && reboot
