#!/bin/bash
#serv=$(echo $0 | awk -F/ '{print $NF}')

if [ -z $1 ]; then
	echo "Using: sw mpd, roon, lms, rompr, airplay, mtroom and other service."
	exit 1
fi
serv=$1
service=$serv
case $1 in
	airplay)
		serv=shairport-sync
		[[ -f /usr/bin/nqptp ]] && service="shairport-sync nqptp" || service="shairport-sync"
		;;
	roon)
		serv=roonserver
		service=roonserver
		;;
	mpd)
		serv=mpd
		service="mpd blissify"
		;;
	mtroom)
		# user="--user"
		serv="owntone"
		service="avahi-daemon mpd owntone blissify"
		;;
	rompr)
		serv=mpd
		service="avahi-daemon mpd nginx php-fpm"
		;;
	lms)
		serv=logitechmediaserver
		service="logitechmediaserver squeezelite"
		;;
esac

if [[ -n $user ]]; then
	[[ $(systemctl is-active --user $serv) == active ]] && systemctl stop --user $service || systemctl start --user $service
else
	if [[ $(systemctl is-active $serv) == active ]]; then 
		sudo systemctl stop $service
	else
		sudo systemctl start $service
		ps H -q `pidof -s mpd` -o 'tid,cls' | grep FF | awk '{print $1}' | while read PROC; do chrt -fp 95 $PROC; done
		ps H -q `pidof -s mpd` -o 'tid,cls' | grep TS | awk '{print $1}' | while read PROC; do chrt -fp 80 $PROC; done
		chrt -fp 85 `pgrep mpd`
	fi
fi

echo Service $service is $(systemctl is-active $user $serv).
