#!/bin/sh
#service=$(echo $0 | awk -F/ '{print $NF}')
serv=$1
service=$1
case $1 in
    airplay)
	serv=shairport-sync
	service="shairport-sync"
	;;
    airplay2)
	serv=shairport-sync
	service="shairport-sync nqptp"
	;;
	roon)
	serv=roonserver
	service=roonserver
	;;
	rompr)
	serv=mpd
	service="mpd nginx php-fpm avahi-daemon"
	;;
	lms)
	serv=logitechmediaserver
	service="logitechmediaserver squeezelite"
	;;
esac
[ $(systemctl is-active $serv) == active ] && sudo systemctl stop $service || sudo systemctl start $service
echo Service $service is $(systemctl is-active $serv).
