#!/bin/bash
#serv=$(echo $0 | awk -F/ '{print $NF}')
if [ -z $1 ]; then
	echo "Using: sw mpd, roon, lms, rompr, airplay, mtroom, hqe, naa and other service."
	exit 1
fi
serv=$1
service=$serv
MPD='mpd '

case $1 in
	airplay)
		serv=shairport-sync
		[[ -f /usr/bin/nqptp ]] && service="shairport-sync nqptp" || service="shairport-sync"
		;;
	roon)
		serv=roonserver
		service=roonserver
		;;
	mpd)
		serv=mpd
		service=$MPD'mpd-plugin'
		;;
	mtroom)
		# user="--user"
		serv="owntone"
		service=$MPD'avahi-daemon owntone mpd-otvol'
		;;
	rompr)
		serv=mpd
		service=$MPD'avahi-daemon nginx php-fpm'
		;;
	mympd)
		serv=mpd
		service=$MPD'mympd'
		;;
	lms)
		serv=logitechmediaserver
		service='logitechmediaserver squeezelite'
		;;
	hqe)
		serv=hqplayerd
		service='hqplayerd'
		;;
	naa)
		serv=networkaudio
		service='networkaudio'
		;;
esac

if [[ -n $user ]]; then
	[[ $(systemctl is-active --user $serv) == active ]] && systemctl stop --user $service || systemctl start --user $service
else
	if [[ $(systemctl is-active $serv) == active ]]; then 
		STATUS='off'
		sudo systemctl stop $service
	else
		STATUS='on'
		sudo systemctl start $service
		if systemctl is-active mpd >/dev/null; then
			chrt -p 93 $(ps H -q $(pidof -s mpd) -o 'tid,cls' | grep FF | awk '{print $1}')
			mpc enable ArchQ >/dev/null 2>&1
			chrt -p 95 $(ps H -q $(pidof -s mpd) -o 'tid,comm' | grep ArchQ | awk '{print $1}')
			chrt -fp 85 $(pgrep mpd)
			chrt -fp 54 $(pgrep ksoftirqd/$(ps -eLo comm,cpuid| grep "output:"|awk '{print $2}'))
			mpc disable Multiroom Stream >/dev/null
		fi
		if systemctl is-active owntone >/dev/null; then
			mpc enable Multiroom >/dev/null
			chrt -p 95 $(ps H -q $(pidof -s mpd) -o 'tid,comm' | grep Multi | awk '{print $1}')
			chrt -p 81 $(pgrep owntone)
			chrt -p 94 $(ps H -q $(pidof -s owntone) -o tid,comm | grep player | awk '{print $1}')
			chrt -p 92 $(ps H -q $(pidof -s owntone) -o tid,comm | grep input | awk '{print $1}')
		fi
	fi
fi

echo Service $service is $'\e[1;38;5;196m'$(systemctl is-active $user $serv)$'\e[m'.
